name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: bank-api

jobs:
  test:
    name: Run Test
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    
    - name: Build Docker image
      run: docker build -t $IMAGE_NAME --target=test .

    - name: Run Test
      run: docker run $IMAGE_NAME
  
  lint:
    needs: test
    name: Run Lint
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    
    - name: Build Docker image
      run: docker build -t $IMAGE_NAME --target=dev .

    - name: Run Test
      run: docker run -it $IMAGE_NAME "npm run lint"

  build:
    needs: lint
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          target: prod
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bank-api:latest
